### ISSUE TITLE
Basic game architecture

### ISSUE THREAD

**Issue by hmil** [turingwars/turingwars#18]
I suggest to change the high level architecture of the game (pages, design and navigation) to allow for:
- Unspecified number of programs (currently, the homepage only allows 5 or 6)
- Easy user-submission of programs
- Easy editing and testing

---

<img width="713" alt="screen shot 2018-08-09 at 6 49 39 pm" src="https://user-images.githubusercontent.com/1753085/43913461-5551e0ba-9c05-11e8-9b4a-cadc994c013d.png">

You land on a page with a long list of all the programs submitted so far (maybe ordered by how good they are, that could be a feature for later, easy way to do a leaderboard too). You can either create a match with existing programs from the list, edit a given program or create a brand new one.

Editing or creating a program takes you to the editor. In the editor, you work on a draft version of your program (maybe in localstorage). You can playtest it against other programs, but you easily navigate from the playtest to the editor and back and forth.
When your program is good enough, you "commit" it, meaning that it now appears in the list.

- No need for login and authentications
- Submitted programs can never be deleted or modified in place
- Very simple extension from where we currently are
- Still allows all cool features we want to be added on top (leaderboard, assembly debugger, ...)

---

Wip on #19

**Comment by nicolasreich** [comment]
Good ideas!

Questions: 
* Do you choose your matches, or is there some matchmaking system that picks an opponent for you depending on some ranking? I think there should be a matchmaking system, otherwise it's too easy to abuse.
* __Submitted programs can never be deleted or modified in place__ means that if you pick a program in the list, modify it, and submit it, you don't actually modify it but rather submit a new one? So you use it as template really, rather than modifying it?
